name: Blog Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
      - name: Check code meets quality standards
        id: code-inspector
        uses: codeinspectorio/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          code_inspector_api_token: ${{ secrets.CODE_INSPECTOR_API_TOKEN }}
          force_ref: "none"
          min_quality_grade: "WARNING"
          min_quality_score: "50"
          max_defects_rate: "0.0001"
          max_complex_functions_rate: "0.0001"
          max_long_functions_rate: "0.0001"
          project_name: ""
          max_timeout_sec: "600"
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/blog
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
        mongodb-version: ["4.4"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm test
